import { Guest } from './types';

export const mockGuests: Guest[] = [
  {
    "id": "G-1001",
    "name": "سليمان العبدالله",
    "phone": "+966 57 618 4007",
    "status": "confirmed",
    "table": "VIP2",
    "companions": 3,
    "isVip": false,
    "category": "colleagues",
    "lastInteraction": "أمس",
    "qrCode": "QR-1001",
    "qrStatus": "expired"
  },
  {
    "id": "G-1002",
    "name": "عبدالرحمن الدوسري",
    "phone": "+966 52 606 5494",
    "status": "checked_in",
    "table": "C2",
    "companions": 0,
    "isVip": false,
    "category": "colleagues",
    "lastInteraction": "اليوم",
    "qrCode": "QR-1002",
    "qrStatus": "expired"
  },
  {
    "id": "G-1003",
    "name": "محمد القحطاني",
    "phone": "+966 50 490 5953",
    "status": "checked_in",
    "table": "C1",
    "companions": 2,
    "isVip": false,
    "category": "other",
    "qrCode": "QR-1003",
    "qrStatus": "expired",
    "notes": "ملاحظة تجريبية للضيف"
  },
  {
    "id": "G-1004",
    "name": "فهد المطيري",
    "phone": "+966 53 341 9248",
    "status": "confirmed",
    "companions": 3,
    "isVip": false,
    "category": "other",
    "qrCode": "QR-1004",
    "qrStatus": "used"
  },
  {
    "id": "G-1005",
    "name": "عمر الشمري",
    "phone": "+966 57 304 9645",
    "status": "maybe",
    "table": "VIP1",
    "companions": 0,
    "isVip": false,
    "category": "family",
    "lastInteraction": "اليوم",
    "qrCode": "QR-1005",
    "qrStatus": "expired"
  },
  {
    "id": "G-1006",
    "name": "فيصل الغامدي",
    "phone": "+966 53 586 5761",
    "status": "maybe",
    "table": "VIP1",
    "companions": 3,
    "isVip": true,
    "category": "colleagues",
    "lastInteraction": "أمس",
    "qrCode": "QR-1006",
    "qrStatus": "used"
  },
  {
    "id": "G-1007",
    "name": "خالد الحربي",
    "phone": "+966 54 899 5343",
    "status": "checked_in",
    "companions": 2,
    "isVip": false,
    "category": "colleagues",
    "lastInteraction": "منذ يومين",
    "qrCode": "QR-1007",
    "qrStatus": "used"
  },
  {
    "id": "G-1008",
    "name": "سعود العتيبي",
    "phone": "+966 56 884 9841",
    "status": "checked_in",
    "table": "B1",
    "companions": 4,
    "isVip": false,
    "category": "colleagues",
    "lastInteraction": "منذ ساعتين",
    "qrCode": "QR-1008",
    "qrStatus": "used",
    "notes": "ملاحظة تجريبية للضيف"
  },
  {
    "id": "G-1009",
    "name": "تركي السبيعي",
    "phone": "+966 50 753 5263",
    "status": "pending",
    "table": "VIP2",
    "companions": 0,
    "isVip": true,
    "category": "family",
    "lastInteraction": "منذ ٣ ساعات",
    "qrCode": "QR-1009",
    "qrStatus": "used"
  },
  {
    "id": "G-1010",
    "name": "نواف الزهراني",
    "phone": "+966 54 976 1695",
    "status": "pending",
    "table": "C1",
    "companions": 3,
    "isVip": false,
    "category": "other",
    "lastInteraction": "اليوم",
    "qrCode": "QR-1010",
    "qrStatus": "used"
  },
  {
    "id": "G-1011",
    "name": "عبدالعزيز الشهراني",
    "phone": "+966 53 466 2502",
    "status": "maybe",
    "companions": 3,
    "isVip": false,
    "category": "colleagues",
    "lastInteraction": "اليوم",
    "qrCode": "QR-1011",
    "qrStatus": "none"
  },
  {
    "id": "G-1012",
    "name": "سلطان العنزي",
    "phone": "+966 58 128 3766",
    "status": "confirmed",
    "table": "C1",
    "companions": 2,
    "isVip": false,
    "category": "friends",
    "lastInteraction": "منذ يومين",
    "qrCode": "QR-1012",
    "qrStatus": "ready",
    "notes": "ملاحظة تجريبية للضيف"
  },
  {
    "id": "G-1013",
    "name": "وليد الجوهري",
    "phone": "+966 57 675 8248",
    "status": "declined",
    "companions": 0,
    "isVip": false,
    "category": "family",
    "lastInteraction": "أمس",
    "qrCode": "QR-1013",
    "qrStatus": "expired"
  },
  {
    "id": "G-1014",
    "name": "بندر الشريف",
    "phone": "+966 58 710 6859",
    "status": "maybe",
    "table": "B1",
    "companions": 2,
    "isVip": false,
    "category": "family",
    "lastInteraction": "منذ يومين",
    "qrCode": "QR-1014",
    "qrStatus": "none"
  },
  {
    "id": "G-1015",
    "name": "ماجد العبيد",
    "phone": "+966 54 816 3479",
    "status": "declined",
    "table": "VIP1",
    "companions": 2,
    "isVip": false,
    "category": "colleagues",
    "lastInteraction": "منذ ٣ ساعات",
    "qrCode": "QR-1015",
    "qrStatus": "expired",
    "notes": "ملاحظة تجريبية للضيف"
  },
  {
    "id": "G-1016",
    "name": "أحمد اليامي",
    "phone": "+966 56 998 5759",
    "status": "pending",
    "companions": 1,
    "isVip": false,
    "category": "other",
    "lastInteraction": "منذ ٣ ساعات",
    "qrCode": "QR-1016",
    "qrStatus": "none"
  },
  {
    "id": "G-1017",
    "name": "ياسر المري",
    "phone": "+966 52 451 9866",
    "status": "declined",
    "table": "A2",
    "companions": 1,
    "isVip": false,
    "category": "colleagues",
    "lastInteraction": "اليوم",
    "qrCode": "QR-1017",
    "qrStatus": "used"
  },
  {
    "id": "G-1018",
    "name": "صالح التميمي",
    "phone": "+966 51 886 3625",
    "status": "maybe",
    "table": "VIP2",
    "companions": 3,
    "isVip": false,
    "category": "friends",
    "lastInteraction": "منذ ٣ ساعات",
    "qrCode": "QR-1018",
    "qrStatus": "expired",
    "notes": "ملاحظة تجريبية للضيف"
  },
  {
    "id": "G-1019",
    "name": "عبدالله الحارثي",
    "phone": "+966 57 544 8895",
    "status": "declined",
    "table": "C1",
    "companions": 0,
    "isVip": false,
    "category": "colleagues",
    "lastInteraction": "منذ ٣ ساعات",
    "qrCode": "QR-1019",
    "qrStatus": "none"
  },
  {
    "id": "G-1020",
    "name": "راكان السالم",
    "phone": "+966 55 704 3832",
    "status": "checked_in",
    "table": "VIP1",
    "companions": 2,
    "isVip": true,
    "category": "friends",
    "qrCode": "QR-1020",
    "qrStatus": "expired"
  },
  {
    "id": "G-1021",
    "name": "فراس المالكي",
    "phone": "+966 50 506 9670",
    "status": "checked_in",
    "companions": 1,
    "isVip": false,
    "category": "friends",
    "lastInteraction": "منذ ساعتين",
    "qrCode": "QR-1021",
    "qrStatus": "none"
  },
  {
    "id": "G-1022",
    "name": "سامي الخالدي",
    "phone": "+966 56 754 9682",
    "status": "confirmed",
    "table": "C2",
    "companions": 3,
    "isVip": false,
    "category": "friends",
    "qrCode": "QR-1022",
    "qrStatus": "ready"
  },
  {
    "id": "G-1023",
    "name": "نايف الشعلان",
    "phone": "+966 50 991 6816",
    "status": "maybe",
    "table": "A1",
    "companions": 4,
    "isVip": false,
    "category": "colleagues",
    "qrCode": "QR-1023",
    "qrStatus": "ready",
    "notes": "ملاحظة تجريبية للضيف"
  },
  {
    "id": "G-1024",
    "name": "طارق البقمي",
    "phone": "+966 58 348 7695",
    "status": "checked_in",
    "table": "C2",
    "companions": 0,
    "isVip": false,
    "category": "other",
    "lastInteraction": "منذ يومين",
    "qrCode": "QR-1024",
    "qrStatus": "used",
    "notes": "ملاحظة تجريبية للضيف"
  },
  {
    "id": "G-1025",
    "name": "بدر القاسم",
    "phone": "+966 54 275 2849",
    "status": "checked_in",
    "table": "A2",
    "companions": 4,
    "isVip": false,
    "category": "friends",
    "qrCode": "QR-1025",
    "qrStatus": "none"
  },
  {
    "id": "G-1026",
    "name": "عبدالمجيد الصيعري",
    "phone": "+966 52 272 2005",
    "status": "checked_in",
    "table": "B3",
    "companions": 0,
    "isVip": false,
    "category": "friends",
    "lastInteraction": "أمس",
    "qrCode": "QR-1026",
    "qrStatus": "ready"
  },
  {
    "id": "G-1027",
    "name": "يزيد العجمي",
    "phone": "+966 53 666 5669",
    "status": "pending",
    "table": "A2",
    "companions": 1,
    "isVip": false,
    "category": "family",
    "lastInteraction": "منذ ٣ ساعات",
    "qrCode": "QR-1027",
    "qrStatus": "used",
    "notes": "ملاحظة تجريبية للضيف"
  },
  {
    "id": "G-1028",
    "name": "سعد السديري",
    "phone": "+966 51 952 5089",
    "status": "checked_in",
    "table": "B1",
    "companions": 1,
    "isVip": false,
    "category": "friends",
    "lastInteraction": "اليوم",
    "qrCode": "QR-1028",
    "qrStatus": "ready",
    "notes": "ملاحظة تجريبية للضيف"
  },
  {
    "id": "G-1029",
    "name": "منصور النصار",
    "phone": "+966 50 975 2972",
    "status": "maybe",
    "table": "VIP2",
    "companions": 3,
    "isVip": false,
    "category": "other",
    "lastInteraction": "منذ يومين",
    "qrCode": "QR-1029",
    "qrStatus": "none"
  },
  {
    "id": "G-1030",
    "name": "ريان الهذلي",
    "phone": "+966 53 888 5474",
    "status": "confirmed",
    "companions": 3,
    "isVip": false,
    "category": "other",
    "lastInteraction": "منذ يومين",
    "qrCode": "QR-1030",
    "qrStatus": "used"
  }
];
